#!/bin/bash
set -e

sudo dnf config-manager \
	    --add-repo \
	    https://download.docker.com/linux/fedora/docker-ce.repo
sudo cp $PWD/repos/google-chrome.repo /etc/yum.repos.d/google-chrome.repo
sudo dnf makecache fast

sudo dnf group install -y "Development Tools"
sudo rpm -e --nodeps vim-minimal
sudo dnf install -y \
	dnf-plugins-core \
	docker-ce \
	python-devel \
	redhat-rpm-config \
	tmux \
	util-linux-user \
	vim-enhanced \
	wget \
	zsh

	# google-chrome-stable \
sudo usermod -aG docker "$USER"
sudo systemctl enable docker
sudo systemctl start docker

pip install --user thefuck awscli
if [ ! -d "$HOME/.zprezto" ]; then
	git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi


wget https://github.com/clvv/fasd/tarball/1.0.1
tar xvzf 1.0.1
rm -f 1.0.1
cd clvv-fasd-4822024
sudo make install
cd ..
rm -rf clvv-fasd-4822024

wget https://github.com/kubernetes/kops/releases/download/1.6.2/kops-linux-amd64 -O kops
sudo mv kops /usr/bin
sudo chmod +x /usr/bin/kops

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
sudo mv kubectl /usr/bin
sudo chmod +x /usr/bin/kubectl

wget https://kubernetes-helm.storage.googleapis.com/helm-v2.5.0-linux-amd64.tar.gz -O helm
tar xvzf helm
sudo cp linux-amd64/helm /usr/bin
sudo chmod +x /usr/bin/helm
rm -rf helm linux-amd64/

if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
fi

mkdir -p ~/.vim/colors


./setup_config

chsh -s /bin/zsh
