#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -z "$TMUX" ]] ;then
    # get the id of a deattached session
    ID="`tmux ls | grep -vm1 attached | cut -d: -f1`"
    # if not available create a new one
    if [[ -z "$ID" ]] ;then
        tmux new-session
    else
        # if available attach to it
        tmux attach-session -t "$ID"
    fi
fi

# Helm
if [[ -x "$(command -v helm)" ]]; then
  source <(helm completion zsh)
fi

source $HOME/.local/bin/aws_zsh_completer.sh

source <(kops completion zsh)

setxkbmap -option caps:escape

# export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh

eval $(~/.linuxbrew/bin/brew shellenv)
